### ISSUE TITLE
Can you help my with matrix parameters?

### ISSUE THREAD

**Issue by max-mykhailenko** [troch/path-parser#4]
Please, add example `path` and `rule` for matrix parameters, can't understand that

**Comment by troch** [comment]
You can look at the tests: https://github.com/troch/path-parser/blob/master/test/main.js#L122-L129

Matrix parameters is something very obscure though, do you have the capabilities to support them with your backend? I am not sure to support them very well. I don't make them optional like query parameters.

They are like regular URL parameters but look more like query parameters (but placed anywhere before `?`). You can define a matrix param by using `;key` instead of `:key` and it will parse them from your URL expecting `;key=value`.

**Comment by max-mykhailenko** [comment]
Thanks!

**Comment by max-mykhailenko** [comment]
I thought, that matrix parameters can resolve my problem. I have object like

``` [
  {setiD: 2, variations: "12-13-4", elements="2-3"},
  {setiD: 4, variations: "11-12-6", elements="2"},
  {setiD: 5, variations: "18-13-8", elements="1"}
]
```

And don't know how I can put it to hash with clear structure

**Comment by max-mykhailenko** [comment]
best idea was `/;set;variations;elements/`, but I can't repeat that pattern multiple times
